name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }

    - name: Install codespell
      run: pip3 install codespell

    - name: Lint
      run: cmake -D FORMAT_COMMAND=clang-format-18 -P cmake/lint.cmake

    - name: Spell check
      if: always()
      run: cmake -P cmake/spell.cmake

  coverage:
    needs: [lint]

    runs-on: ubuntu-24.04

    if: github.repository_owner == '<name>' && false

    steps:
    - uses: actions/checkout@v4

    - name: Install LCov
      run: sudo apt-get update -q && sudo apt-get install lcov -q -y
      
    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y -q \
          libboost-all-dev \
          clang \
          llvm \
          pkg-config \
          catch2 \
          libabsl-dev \
          libxml2-dev \
          libffi-dev \
          libtinfo-dev

    - name: Configure
      run: cmake --preset=ci-coverage

    - name: Build
      run: cmake --build build/coverage -j 2

    - name: Test
      working-directory: build/coverage
      run: ctest --output-on-failure --no-tests=error -j 2

    - name: Process coverage info
      run: cmake --build build/coverage -t coverage

    - name: Submit to codecov.io
      uses: codecov/codecov-action@v4
      with:
        file: build/coverage/coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}

  sanitize:
    needs: [lint]

    runs-on: ubuntu-24.04

    env: { CXX: clang++-18 }

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y -q \
          libboost-all-dev \
          clang \
          llvm \
          pkg-config \
          catch2 \
          libabsl-dev \
          libxml2-dev \
          libffi-dev \
          libtinfo-dev

    - name: Configure
      run: cmake --preset=ci-sanitize

    - name: Build
      run: cmake --build build/sanitize -j 2

    - name: Test
      working-directory: build/sanitize
      env:
        ASAN_OPTIONS: "strict_string_checks=1: detect_stack_use_after_return=1: check_initialization_order=1: strict_init_order=1: detect_leaks=1: halt_on_error=1"
        UBSAN_OPTIONS: "print_stacktrace=1: halt_on_error=1"
      run: ctest --output-on-failure --no-tests=error -j 2

  test:
    needs: [lint]

    strategy:
      matrix:
        os: [ubuntu-24.04]
        type: [shared, static]
        include:
        - { type: shared, shared: YES }
        - { type: static, shared: NO }

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-24.04'
      run: |
        sudo apt-get update -q
        sudo apt-get install -y -q \
          libboost-all-dev \
          clang \
          llvm \
          pkg-config \
          catch2 \
          libabsl-dev \
          libxml2-dev \
          libffi-dev \
          libtinfo-dev

    - name: Install static analyzers
      if: matrix.os == 'ubuntu-24.04'
      run: |
        while sudo fuser /var/lib/dpkg/lock-frontend; do
          echo "Waiting for other apt processes to finish..."
          sleep 1
        done
        sudo apt-get install clang-tidy-18 cppcheck -y -q
        sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-18 180

    - name: Configure
      shell: pwsh
      run: cmake "--preset=ci-$("${{ matrix.os }}".split("-")[0])" -D BUILD_SHARED_LIBS=${{ matrix.shared }}

    - name: Build
      run: cmake --build build --config Release -j 2

    - name: Install
      run: cmake --install build --config Release --prefix prefix

    - name: Test
      working-directory: build
      run: ctest --output-on-failure --no-tests=error -C Release -j 2
